Move EC check into options parsing block.

diff --git a/mkcert b/mkcert
--- a/mkcert
+++ b/mkcert
@@ -74,6 +74,11 @@ while true; do
     -E|--curve)
         CURVE="$1"
         shift 1
+
+        if ! openssl ecparam -name "$CURVE" -noout 2> /dev/null; then
+            echo "Invalid curve: $CURVE" >&2
+            exit 1
+        fi
         ;;
     -y|--years)
         YEARS="$1"
@@ -203,11 +208,6 @@ subjectAltName = DNS:$COMMON_NAME
 EOF
 
 if [[ -n $CURVE ]]; then
-    if ! openssl ecparam -name "$CURVE" -noout 2> /dev/null; then
-        echo "Invalid curve: $CURVE" >&2
-        exit 1
-    fi
-
     if ! openssl ecparam -name "$CURVE" -genkey -noout \
          -out "$TEMP_DIR/key.pem" 2> /dev/null; then
         echo "Error while generaing EC key" >&2
